version: '3.7'

services:
  postgres:
    image: postgres:10.7
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  node:
    build:
      context: .
      target: base
    environment:
      - APP_NAME
      - DB_HOSTNAME
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - NODE_ENV
      - SERVER_PORT
    user: "1000:1000"
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ".:/node:rw"
      - "./dist/public:/node/src/server/client:ro"
    command: ["npm", "run", "start:dev"]
    links:
      - postgres
    depends_on:
      - "postgres"
volumes:
  postgres_data:
