version: '3.7'

services:
  postgres:
    image: postgres:10.7
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  node:
    build:
      context: .
      target: base
    environment:
      - APP_NAME
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASS
      - NODE_ENV
      - SERVER_PORT
    user: "1000:1000"
    ports:
      - "127.0.0.1:${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ".:/node:rw"
      - "./dist/public:/node/src/server/client:ro"
    command: ["npm", "run", "start:dev"]
    links:
      - postgres
    depends_on:
      - "postgres"
volumes:
  postgres_data:
